import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Container from '@/components/Container'
import Header from '@/components/Header'
import Button from '@/components/Button'
import styles from '@/styles/Home.module.scss'
import items from '@/data/items.json'
export default function Home() {
  return (
    <div >
      <Head>
        <title>Small Breed Wonders</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.3.3/default/snipcart.css" />
      </Head>

      <Header />
      <main id="main">
        <Container className={styles.Home}>
          <h1> Space Balls Jumbolaya </h1>
          <h2> Available Cards </h2>
          <ul className={styles.products}>
            {items.map(item => {
              return (
                <li key={item.id}>
                  <Image width="864" height="1200" src={item.image} alt="Bowser Holographic" />
                  <h3>{item.title}</h3>
                  <p>${item.price}</p>
                  <Button className="snipcart-add-item"
                    data-item-id={item.id}
                    data-item-price={item.price}
                    data-item-url="/"
                    data-item-description=""
                    data-item-image={item.image}
                    data-item-name={item.title}
                  
                  >Add to Cart</Button>
                </li>
              )
            })}




          </ul>
        </Container>
      </main>

      <footer className={styles.footer}>
        &copy; Small Breed Wonders, {new Date().getFullYear()}
      </footer>
      <Script src="https://cdn.snipcart.com/themes/v3.3.3/default/snipcart.js" />
      <div hidden id="snipcart" data-api-key="process.env.SNIPCART_API_KEY"></div>
      {/* <div hidden id="snipcart" data-api-key="NTFkZTllYmYtMjhiMS00ZTIxLWE4YjktOTI2ZjM2NTQ4YWYzNjM3ODI1NjAyODAyNjI2MzE4"></div> */}
    </div>
  )
}
